<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ListaryOpen.App\ListaryOpen.App.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Release' And '$(RuntimeIdentifier)' != ''">true</PublishReadyToRun>
  </PropertyGroup>

</Project>
